export const res = {
  status: "success",
  result: {
    query_id: "f5177242-2947-4577-880e-871716bc05f9",
    answer: "Montréal Hotel & Suits was built in 2010 by John Smith.",
    elected_facts: [
      {
        attachments: [],
        subtopic: "General information",
        subtopic_desc: "This is about the hotel, its history and quality.",
        text: "Montréal Hotel & Suits was built in 2010 by John Smith",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
        tagged_slots: [],
      },
    ],
    entities: [],
    top_facts: [
      {
        attachments: [],
        subtopic: "General information",
        subtopic_desc: "This is about the hotel, its history and quality.",
        text: "Montréal Hotel & Suits was built in 2010 by John Smith",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Safety",
        subtopic_desc: "This is about the hotel neighborhood and your safety during your stay.",
        text: "The hotel has no medical staff onsite, but is located within 5 minutes of the hospital",
        topic: "Area / Around",
        topic_desc: "This is about the area around the hotel and surrounding activities.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "General information",
        subtopic_desc: "This is about the hotel, its history and quality.",
        text: "The hotel is located at 1045 Peel street in downtown Montréal. The hotel is at the intersection of Peel and Saint-Catherine streets and the postal code is G8L 9F5.",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Social Media (instagram, etc)",
        subtopic_desc: "This is about where you can find us on social medias.",
        text: "The hotel is present on Instagram as @montreal_hotel (Montreal Hotel & Suites)",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "How to move around (taxi, bus, metro)",
        subtopic_desc: "This is about transportation and how to move around from the hotel.",
        text: "The hotel is near the York metro station",
        topic: "Area / Around",
        topic_desc: "This is about the area around the hotel and surrounding activities.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Airport Shuttle",
        subtopic_desc: "This is about transportation from/to the airport.",
        text: "The hotel is located within 50 miles of the airport",
        topic: "Area / Around",
        topic_desc: "This is about the area around the hotel and surrounding activities.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "General information",
        subtopic_desc: "This is about the hotel, its history and quality.",
        text: "The hotel has 110 rooms and 15 floors",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Restaurant: La poule mouillée",
        subtopic_desc: 'This is about the hotel restaurant "La poule mouillée".',
        text: 'The hotel has a restaurant (called "La poule mouillée") on the 1st floor',
        topic: "Restaurants",
        topic_desc: "This is information about our hotel restaurants.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Attractions",
        subtopic_desc: "This is about top attractions and tourism around the city and nearby the hotel.",
        text: "The hotel is close to several attractions such as: the Hello World art museum, the A-Star Olympic Stadium, the McGill college and the Botpress Montréal offices.",
        topic: "Area / Around",
        topic_desc: "This is about the area around the hotel and surrounding activities.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Restaurant: La poule mouillée",
        subtopic_desc: 'This is about the hotel restaurant "La poule mouillée".',
        text: "Guests can put their restaurant orders on their room bill and pay at check-out",
        topic: "Restaurants",
        topic_desc: "This is information about our hotel restaurants.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Attractions",
        subtopic_desc: "This is about top attractions and tourism around the city and nearby the hotel.",
        text: "There are dozens of great restaurants within walking distance",
        topic: "Area / Around",
        topic_desc: "This is about the area around the hotel and surrounding activities.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "General information",
        subtopic_desc: "This is about the hotel, its history and quality.",
        text: "The hotel has a 4 star rating",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "General information",
        subtopic_desc: "This is about the hotel, its history and quality.",
        text: "The hotel main phone number is (514)-111-2222. The hotel website is www.montreal-hotel.com. The hotel email address is contact@montreal-hotel.com",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Commitments / Sustainability",
        subtopic_desc: "This is about our commitments, social responsibilities and sustainability goals.",
        text: "Here are the actions we take to help reduce our carbon footprint: (1) Towels are washed only when guests put them on the floor and (2) Lights are automatically shut off when leaving the room",
        topic: "About",
        topic_desc: "This is more information about the hotel.",
        slot_defs: [],
      },
      {
        attachments: [],
        subtopic: "Services / Features / Amenities",
        subtopic_desc: "This is about amenities, services and features available for business.",
        text: "The hotel has a fax, printer, copier available",
        topic: "Business",
        topic_desc: "This is about how the hotel can accomodate your business trip.",
        slot_defs: [],
      },
    ],
    remaining_queries: 0,
  },
};
